import os
import time
import itertools
import threading
import sys
import subprocess


print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print("░▄▀▀")
time.sleep(0.1)
print("░▀▄▄")
time.sleep(0.1)
print("█▄▒▄█")
time.sleep(0.1)
print("█▒▀▒█")
time.sleep(0.1)
print("▒▄▀▄░")
time.sleep(0.1)
print("░█▀█░")
time.sleep(0.1)
print("░▀█▀▒")
time.sleep(0.1)
print("░█▄▄░")
time.sleep(0.1)
print("▒██▀░")
time.sleep(0.1)
print("░█▄▄░")
time.sleep(0.1)
print("░▀▄▀░░")
time.sleep(0.1)
print("░▒█▒▒░")
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print("░▄▀▀░")
time.sleep(0.1)
print("░▀▄▄░")
time.sleep(0.1)
print("░▄▀▄░")
time.sleep(0.1)
print("░▀▄▀░")
time.sleep(0.1)
print("░█▄▒▄█░")
time.sleep(0.1)
print("░█▒▀▒█░")
time.sleep(0.1)
print("░█▄▒▄█░")
time.sleep(0.1)
print("░█▒▀▒█░")
time.sleep(0.1)
print("▒▄▀▄░")
time.sleep(0.1)
print("░█▀█░")
time.sleep(0.1)
print("░█▄░█░")
time.sleep(0.1)
print("░█▒▀█▒")
time.sleep(0.1)
print("░█▀▄░░")
time.sleep(0.1)
print("▒█▄▀▒░")
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print("░░█▒░░")
time.sleep(0.1)
print("░▒█▄▄░")
time.sleep(0.1)
print("░█░")
time.sleep(0.1)
print("░█░")
time.sleep(0.1)
print("░█▄░█▒")
time.sleep(0.1)
print("░█▒▀█░")
time.sleep(0.1)
print("▒██▀░░")
time.sleep(0.1)
print("░█▄▄▒░")
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print("░▒█▀▄░")
time.sleep(0.1)
print("░░█▀▒░")
time.sleep(0.1)
print("░▀▄▀░")
time.sleep(0.1)
print("░▒█▒░")
time.sleep(0.1)
print("░▀█▀░")
time.sleep(0.1)
print("░▒█▒▒")
time.sleep(0.1)
print("░█▄█░")
time.sleep(0.1)
print("▒█▒█░")
time.sleep(0.1)
print("░▄▀▄░")
time.sleep(0.1)
print("░▀▄▀░")
time.sleep(0.1)
print("░█▄░█░")
time.sleep(0.1)
print("░█▒▀█▒")
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print("░▒██▀░")
time.sleep(0.1)
print("░░█▄▄▒")
time.sleep(0.1)
print("░█▀▄░")
time.sleep(0.1)
print("▒█▄▀░")
time.sleep(0.1)
print("░█░")
time.sleep(0.1)
print("░█░")
time.sleep(0.1)
print("░▀█▀░")
time.sleep(0.1)
print("░▒█▒░")
time.sleep(0.1)
print("░█░")
time.sleep(0.1)
print("░█░")
time.sleep(0.1)
print("░▄▀▄░")
time.sleep(0.1)
print("░▀▄▀░")
time.sleep(0.1)
print("░█▄░█")
time.sleep(0.1)
print("░█▒▀█")
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
print()
time.sleep(0.1)
subprocess.call('cls', shell=True)
print("LOADING COMPLETED!!!")
time.sleep(1)
print()

done = False

def animate():
    for c in itertools.cycle(['|', '/', '-', '\\']):
        if done:
            break
        sys.stdout.write('\rLoading Repl ' + c)
        sys.stdout.flush()
        time.sleep(0.1)
    sys.stdout.write('\rLoading Repl completed!')
t = threading.Thread(target=animate)
t.start()

time.sleep(5)
done = True

time.sleep(3)
print()

os.chdir('rere') # Changes Directory
try:
    subprocess.call('python pycmd.py', shell=False) # Loads in Directory
except:
    subprocess.call('python pycmd.py', shell=True) # Same command, but for the shell