import time
import os
clear = False
Commandline = False

#THIS FAKE REPL IS MADE BY CMAZEY!!!

checkup = input("Are you sure you want to proceed? (yes) -> ")

if checkup == "yes":
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print("Please hold...")
    time.sleep(10)
    os.system('cls')
    clear = True
else:
    print("\nRequest Terminated...\n\n")

while(clear):
    time.sleep(1)
    print("-- WINDOWS COMMAND LINE *Python Version* --")
    time.sleep(0.1)
    print("REPL RECREATED BY COLTON MAZEY AKA 'CMAZEY'\n")
    time.sleep(2)
    print("WARNING: This recreated command line is NOT finished, This command line will be constantly updated, please check the Github site to check for recent updates, thanks!")
    time.sleep(1)
    print("Version: PRE ALPHA: v1.0.4")
    time.sleep(3)
    print()
    time.sleep(1)
    name = input("Please enter your username: ")
    time.sleep(1)
    print(f"Username entered: {name}\n")
    time.sleep(0.1)
    print("Creating REPL, please hold...")
    time.sleep(3)
    print("Progress: 5%")
    time.sleep(1)
    print("Progress: 16%")
    time.sleep(1)
    print("Progress: 27%")
    time.sleep(1)
    print("Progress: 39%")
    time.sleep(1)
    print("Progress: 43%")
    time.sleep(5)
    print("Progress: 52%")
    time.sleep(2)
    print("Progress: 62%")
    time.sleep(0.1)
    print("Progress: 67%")
    time.sleep(0.1)
    print("Progress: 71%")
    time.sleep(0.1)
    print("Progress: 78%")
    time.sleep(0.1)
    print("Progress: 82%")
    time.sleep(0.1)
    print("Progress: 85%")
    time.sleep(0.1)
    print("Progress: 89%")
    time.sleep(0.1)
    print("Progress: 93%")
    time.sleep(0.1)
    print("Progress: 95%")
    time.sleep(0.1)
    print("Progress: 96%")
    time.sleep(0.1)
    print("Progress: 97%")
    time.sleep(1)
    print("Progress: 98%")
    time.sleep(1)
    print("Progress: 99%")
    time.sleep(1)
    print("Progress: 100%")
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print()
    time.sleep(0.1)
    print()

    

    os.system('cls')
    time.sleep(3)

    print("Microsoft Windows [Version 10.0.22000.493]")
    print("(c) Microsoft Corporation. All rights reserved.")
    time.sleep(2)
    print()
    time.sleep(1)
    print("HINT: use the 'help' command to check out all the available commands!") #Delete this command if you don't want to see this popup.
    time.sleep(1)
    clear = False
    Commandline = True

    while(Commandline):
        cmdanswer = input(f"C:/Users/{name}> ")

        if cmdanswer == "help":
            time.sleep(1)
            print("\nhelp")
            print("sad")
            print("test")
            print("clear")
            print("exit")
            print("play")
            print("version")
            print("currentdir")
            print("More coming soon..")
            time.sleep(2)
            print()
            time.sleep(1)
        elif cmdanswer == "test":
            time.sleep(0.1)
            print("\nThis is a test...\n")
            time.sleep(1)
        elif cmdanswer == "sad":
            print()
            time.sleep(1)
            print("Someone named Braedon had made me sad because he was given the role to use the sound effect and yeah. : ( ")
            time.sleep(3)
            print()
            time.sleep(1)
        elif cmdanswer == "clear":
            os.system('cls')
            time.sleep(1)
            print("Microsoft Windows [Version 10.0.22000.493]")
            print("(c) Microsoft Corporation. All rights reserved.")
            time.sleep(1)
            print()
            time.sleep(0.1)
        elif cmdanswer == "exit":
            time.sleep(1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print("Command")
            time.sleep(0.1)
            print("Line")
            time.sleep(0.1)
            print("Reimagined")
            time.sleep(0.1)
            print("By")
            time.sleep(0.1)
            print("Colton")
            time.sleep(0.1)
            print("Mazey!")
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            time.sleep(0.1)
            print()
            Commandline = False

        elif cmdanswer == "play":
                time.sleep(2)

                os.system('cls')

                time.sleep(3)
                print("Please choose the following:")
                time.sleep(0.1)
                print()
                time.sleep(1)
                print("- bee")
                time.sleep(0.1)
                print("- Upd-11/15")
                time.sleep(0.1)
                print("- exit")

                time.sleep(1)
                print()
                time.sleep(2)

                playplay = True

                while playplay:
                    playanswer = input("-> ")
                #Start Play
                    if playanswer == "bee":
                        #This may take about 2 to 5 minutes
                        time.sleep(1)
                        os.system('cls')
                        time.sleep(3)
                        print("The EDWARDIAN PLAYERS Present")
                        time.sleep(2)
                        print("The 25th Annual Putnam County SPELLING BEE")
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("MUsic and Lyrics by: William Finn")
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("Book by: Rachel Sheinkin")
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("Conceived by: Rebecca Feldman")
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("This show goes through November 17, 2022 to November 20, 2022!")
                        time.sleep(1)
                        print()
                        time.sleep(4)
                        print()
                        time.sleep(1)
                        print("--- CAST MEMBERS (in order of appearance) ---")
                        time.sleep(1)
                        print("^ indicates Magnificat High School students, * indicates Saint Joseph Academy students, (BF) indicates developer best friend")
                        time.sleep(3)
                        print()
                        time.sleep(1)
                        #CAST MEMBERS
                        print("Rona Lisa Peretti - ELLA SONBY")
                        time.sleep(1)
                        print("Chip Tolentino - COLIN WHEELER")
                        time.sleep(1)
                        print("Logainne SchwartzandGrubenierre - HALEY BETTERS^")
                        time.sleep(1)
                        print("Leaf Coneybear - THOMAS LOPEZ")
                        time.sleep(1)
                        print("William Barfee - ADAM DEMPSEY")
                        time.sleep(1)
                        print("Marcy Park - HELEN GERRITY*")
                        time.sleep(1)
                        print("Olive Ostrovsky - PAIGE BRADFORD^")
                        time.sleep(1)
                        print("Vice Principal Douglas Panch - CODY WAGNER")
                        time.sleep(1)
                        print("Mitch Mahoney - JUSTIN SALAZAR")
                        time.sleep(1)
                        print("Carl Dad - DANNY CERTO")
                        time.sleep(1)
                        print("Dan Dad - CONALL McMAHON")
                        time.sleep(4)
                        print()
                        time.sleep(1)
                        print("--- CREW ---")
                        time.sleep(4)
                        print()
                        time.sleep(1)
                        #STAGE AND CREW MANAGER
                        print("Stage Manager - Lillie Forbes^")
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("Crew Manager - Johstan Kuehner (BF)")
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("-- STAGE CREW --")
                        #STAGE CREW
                        time.sleep(3)
                        print()
                        time.sleep(1)
                        print("Braeden Barker (BF)")
                        time.sleep(1)
                        print("Sean Dabydeen")
                        time.sleep(1)
                        print("William Graham")
                        time.sleep(1)
                        print("Xannie Gray^")
                        time.sleep(1)
                        print("Julia Houghtling*")
                        time.sleep(1)
                        print("Erin Houghtling*")
                        time.sleep(1)
                        print("Pasha Manley")
                        time.sleep(1)
                        print("Colton Mazey (DEV)")
                        time.sleep(1)
                        print("Alycia McGill*")
                        time.sleep(1)
                        print("Johnny Mendoza")
                        time.sleep(1)
                        print("Max Miron")
                        time.sleep(1)
                        print("Sarah Molseed^")
                        time.sleep(1)
                        print("Elijah Molseed (BF)")
                        time.sleep(1)
                        print("Daniel Monahan")
                        time.sleep(1)
                        print("Clare Monahan (2027)")
                        time.sleep(1)
                        print("Scott O'Neill (BF)")
                        time.sleep(1)
                        print("Brandon Reed (BF)")
                        time.sleep(1)
                        print("Dante Scott (BF)")
                        time.sleep(1)
                        print("Andy Scott (BF)")
                        time.sleep(1)
                        print("Reuben Shaffer III")
                        time.sleep(1)
                        print("Ori Turner")
                        time.sleep(1)
                        print()
                        time.sleep(2)
                        print("--- ORCHESTRA ---")
                        time.sleep(4)
                        print()
                        time.sleep(1)
                        #ORCHESTRA/BAND
                        print("David Michaels - Keyboard 1")
                        time.sleep(1)
                        print("Harry Richardson - Synthesizer")
                        time.sleep(1)
                        print("Eli Weiskirch - Reed")
                        time.sleep(1)
                        print("Hannah Benjamin - Cello")
                        time.sleep(1)
                        print("Stephen Martis - Percussion")
                        time.sleep(1)
                        print()
                        time.sleep(2)
                        print("--- STAFF ---")
                        time.sleep(4)
                        print()
                        #STAFF
                        time.sleep(1)
                        print("Director - Tony Heffner '13")
                        time.sleep(1)
                        print("Technical Director - John F. Goers '78")
                        time.sleep(1)
                        print("Master Carpenter - Matt O'Konowitz '01")
                        time.sleep(1)
                        print("Choreographer - Sarah Heffner")
                        time.sleep(1)
                        print("Music Director - Dave Michaels '03")
                        time.sleep(1)
                        print("Props Master - Cari Foster and Joseph Basalla '15")
                        time.sleep(1)
                        print("Lighting Design and Rigging - Corey Farr '12")
                        time.sleep(1)
                        print("Costume Design - Melody Walker")
                        time.sleep(1)
                        print("Technical Assistant - John Karliak '56, Sean Monahan '93, and Emily Hetman")
                        time.sleep(1)
                        print("Business Manager/Program/Box Office - Connie Massie")
                        time.sleep(0.1)
                        print()
                        time.sleep(5)
                        print()
                        time.sleep(1)     
                    elif playanswer == "upd-11/15":
                        #This update occured at November 15, 2022
                        time.sleep(1)
                        print()
                        time.sleep(1)
                        print("About half of the Mics were about dead, the show still went on but the audio will be quieter than before.")
                        time.sleep(5)
                        print()
                        time.sleep(1)
                    elif playanswer == "newsies":
                        print("Coming soon...")
                        time.sleep(1)
                    elif playanswer == "exit":
                        time.sleep(1)
                        print()
                        time.sleep(3)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print("exited")
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)
                        print()
                        time.sleep(0.1)

                        playplay = False
                    elif playanswer == "help":
                        time.sleep(1)
                        print("'bee' - SPELLING BEE PLAY (FALL 2022)")
                        print("'upd-11/15 - Updates from November 15, 2022")
                        print("'help' - Displays the available commands")
                        print("newsies - DISNEY NEWSIES: THE BROADWAY MUSICAL")
                        print("exit")
                        time.sleep(4)
                        print()
                        time.sleep(1)
                    else:
                        print("Invalid, please try again...")
                        time.sleep(1)
                        print()
                        time.sleep(0.1)
        #End of "Play"
        elif cmdanswer == "version:":
            time.sleep(0.1)
            print("REPL Version: v2.4.3")
            time.sleep(3)
        elif cmdanswer == "currentdir":
            print("Current Directory:", os.getcwd())
            time.sleep(1)
        else:
            print()


